#############################################################
## Verify det(σ(β·cond_O)) = M(f)^(d-1)·|det(V)|^3          ##
## where cond_O = {x ∈ K | x·O_K ⊆ O}, O = Z[a]           ##
## f: monic irreducible polynomial (need not be monogenic)  ##
#############################################################

load("random_polynomials.sage")
load("test_monogenic.sage")
load("compute_dual_basis.sage")
load("test_Vandermonde.sage")



def compute_conductor_basis(K):
    """
    Compute a Z-basis for the conductor ideal
        cond_O = {x in K | x * O_K ⊆ O},
    where O = Z[a] is the monogenic order generated by the primitive element a
    and O_K is the full ring of integers of K.

    The conductor satisfies  cond_O = f'(a) * O_K^∨,  where O_K^∨ is the
    codifferent (the Z-dual of O_K with respect to the trace pairing).
    A Z-basis of O_K^∨ is the trace-dual basis {β_0,...,β_{d-1}} of the
    integral basis of O_K, i.e. the unique elements satisfying
        Tr(b_i * β_j) = δ_{ij}  for all i,j.
    Hence a Z-basis of cond_O is  {f'(a) * β_i  |  i = 0,...,d-1}.

    Input:
        K - NumberField (K = QQ[a], a root of an irreducible monic f)

    Output:
        basis - list of d elements of K forming a Z-basis of cond_O
    """
    d = K.degree()
    a = K.gen()
    f = K.defining_polynomial()

    # f'(a) in K
    diff_gen = f.derivative()(a)          # = f'(a)

    # Compute the trace-dual (codifferent) basis of O_K.
    # OK_basis = {b_0, ..., b_{d-1}} is a Z-basis of O_K.
    # The dual basis {β_i} satisfies Tr(b_i * β_j) = δ_{ij}.
    # We solve for it via the inverse of the trace-form Gram matrix.
    OK_basis = K.ring_of_integers().basis()   # list of d elements in K
    F = K.base_ring()                         # = QQ
    # Gram matrix G[i,j] = Tr(b_i * b_j)
    G = matrix(F, d, d, [(OK_basis[i] * OK_basis[j]).trace()
                         for i in range(d) for j in range(d)])
    G_inv = G.inverse()
    # Dual basis: β_j = sum_k G_inv[k,j] * b_k
    dual_OK_basis = [sum(G_inv[k, j] * OK_basis[k] for k in range(d))
                     for j in range(d)]

    # cond_O = f'(a) * O_K^∨  =>  Z-basis is {f'(a) * β_i}
    conductor_basis = [diff_gen * beta for beta in dual_OK_basis]

    return conductor_basis


def compute_sigma_matrix(basis, embeddings, CCprec):
    """
    Compute the matrix whose rows are sigma_i(basis_j) for all embeddings sigma_i
    and basis elements basis_j.
    
    Input:
        basis - list of basis elements in K
        embeddings - list of embeddings K: sigma_i(x)
    
    Output:
        M - matrix where M[i,j] = sigma_i(basis[j])
    """
    d = len(basis)
    
    # Create matrix where each row corresponds to an embedding
    # and each column corresponds to a basis element
    M = matrix(CCprec, d, d)
    
    for i, sigma in enumerate(embeddings):
        for j, b in enumerate(basis):
            M[i, j] = sigma(b)
    
    return M

def compute_mahler_measure(alphas, verbose=False):
    """
    Compute the Mahler measure M(f) := product of max{1, |alpha_i|}
    where alpha_i are the roots of f.
    
    Input:
        alphas - list of roots of f
        verbose - whether to print details
    
    Output:
        M_f - Mahler measure ( = Π max{1, |alpha_i|})
    """
    RR = RealField()
    d = len(alphas)
    
    # Compute max{1, |alpha_i|} for each root
    target_values = [max(RR(1), abs(alpha)) for alpha in alphas]
    
    # Compute product
    log_Mf = RR(0)
    for val in target_values:
        log_Mf += log(val)
    
    if verbose:
        print("\nMahler measure computation:")
        print(f"  Roots: {[complex(r) for r in roots[:3]]}")
        print(f"  |alpha_i|: {[float(abs(r)) for r in roots]}")
        print(f"  max{{1, |alpha_i|}}: {[float(v) for v in target_values]}")
        print(f"  M(f) = Π max{{1, |alpha_i|}} = {float(exp(log_Mf))}")

    return target_values,log_Mf



def verify_equation_derivation(f, K, verbose=False, precision = 1000):
    """
    Verify the equation derivation in strict order:
    1. Check |Δ_K| = |det(V)|^2
    2. Check det(σ(cond_O)) = |N(f'(a))| · |Δ_K|^{-1/2}
       where cond_O = {x in K | x*O_K ⊆ O} = f'(a)·O_K^∨, O = Z[a]
    3. Check det(σ(β·cond_O)) = M(f)^(d-1) · det(σ(cond_O))
                               = M(f)^(d-1) · |N(f'(a))| · |Δ_K|^{-1/2}

    Input:
        f - polynomial defining K (monic irreducible; need not be monogenic)
        K - number field
        verbose - whether to print detailed verification
    """
    d = f.degree()
    CCprec = ComplexField(precision)
    verify_equation_false = False

    # ========================================================
    # Verification using Logarithms
    # ========================================================
    # We compare log(LHS) and log(RHS) to avoid overflow
    
    # 1. Check |Δ_K| = |det(V)|^2
    log_Delta_K = log(abs(K.discriminant()))

    # Vandermonde
    V = Vf(f,precision = precision)
    log_det_V = log(abs(V.determinant()))
    if(abs(log_Delta_K - 2*log_det_V) > 1e-3):
        verify_equation_false = True
        print("================================")
        print("1. [Failed] Check |Δ_K| != |det(V)|^2")
        print("log(|Δ_K|) = ", round(log_Delta_K,2))
        print("log(|det(V)|^2) = ", round(2*log_det_V,2))


    # 2. Check det(σ(cond_O)) = |N(f'(a))| · |Δ_K|^{-1/2}
    # Compute roots
    alphas = f.roots(ring = CCprec, multiplicities = False)
  

    # Conductor ideal basis: cond_O = {x in K | x*O_K ⊆ O}, O = Z[a]
    conductor_basis = compute_conductor_basis(K)
    # sigma_matrix_conductor: σ(cond_O)
    sigma_matrix_conductor = compute_sigma_matrix(conductor_basis, K.embeddings(CCprec), CCprec)
    det_sigma_conductor = sigma_matrix_conductor.determinant()
    log_det_sigma_conductor = log(abs(det_sigma_conductor))
    # Since cond_O = f'(a) * O_K^∨ and |det(σ(O_K^∨))| = |Δ_K|^{-1/2}:
    #   |det(σ(cond_O))| = |N_{K/Q}(f'(a))| * |Δ_K|^{-1/2}
    a_gen = K.gen()
    f_prime_a = f.derivative()(a_gen)     # f'(a) in K
    log_N_f_prime_a = log(abs(RR(f_prime_a.norm())))
    expected_log_det_sigma_conductor = log_N_f_prime_a - 0.5 * log_Delta_K
    if(abs(log_det_sigma_conductor - expected_log_det_sigma_conductor) > 1e-3):
        verify_equation_false = True
        print("================================")
        print("2. [Failed] Check det(σ(cond_O)) != |N(f'(a))| · |Δ_K|^{-1/2}")
        print("log(|det(σ(cond_O))|) = ", round(log_det_sigma_conductor,2))
        print("log(|N(f'(a))| · |Δ_K|^{-1/2}) = ", round(expected_log_det_sigma_conductor,2))

    # 3. Check det(σ(β·cond_O)) = M(f)^(d-1) · det(σ(cond_O))
    # Mahler measure
    target_values, log_Mf = compute_mahler_measure(alphas, verbose=False)
    # Compute log_Mf_pow consistently with scaling factors
    log_Mf_pow = log_Mf * (d-1)
    
    # Matrix σ(β·cond_O)
    rows = []
    for i in range(d):
        # σ(β·cond_O) = diag(σ(β))·σ(cond_O)
        factor = target_values[i]^(d-1)
        row = [factor * x for x in sigma_matrix_conductor.row(i)]
        rows.append(row)
    
    sigma_matrix_beta_conductor = matrix(CCprec, rows)
   
    det_sigma_beta_conductor = sigma_matrix_beta_conductor.determinant()
    log_det_sigma_beta_conductor = log(abs(det_sigma_beta_conductor))
    
    # Expected: |det(σ(β·cond_O))| = M(f)^(d-1) · |det(σ(cond_O))|
    #                               = M(f)^(d-1) · |N(f'(a))| · |Δ_K|^{-1/2}
    expected_log_det = log_Mf_pow + expected_log_det_sigma_conductor
    if(abs(log_det_sigma_beta_conductor - expected_log_det) > 1e-3):
        verify_equation_false = True 
        print("================================")
        print("3. [Failed] Check det(σ(β·cond_O)) != M(f)^(d-1)·|N(f'(a))|·|Δ_K|^{-1/2}")
        print("log(det(σ(β·cond_O))) = ", round(log_det_sigma_beta_conductor,2))
        print("log(M(f)^(d-1)·|N(f'(a))|·|Δ_K|^{-1/2}) = ", round(expected_log_det,2))

    return verify_equation_false

def verifications_sigma_beta_equation(nb_tests, degree, size_poly, precision = 1000):
    """
    Verify the sigma-beta equation for `nb_tests` random monic irreducible
    polynomials of the given degree and coefficient size.
    f need NOT be monogenic.
    """
    verify_equation_false = False
    t = 0
    fs = []
    Zx.<X> = ZZ[]
    while(t < nb_tests):
        # Generate a random monic irreducible polynomial (no monogenic requirement)
        f = unif_poly(degree, B = size_poly)
        if f in fs:
            continue
        fs.append(f)
        K = NumberField(f, 'a')
        if(verify_equation_derivation(f, K, precision = precision)):
            verify_equation_false = True
            break
        t += 1
    return verify_equation_false

